### ISSUE TITLE
Rename james.data.xml.clss to james.format.xml.clss

### ISSUE THREAD

**Issue by mdbs99** [mdbs99/james#14]
Rename `james.data.xml.clss` to `james.text.xml.clss`.

Everything that is a text should be inside james.text.* directory.
For example
- james.text.xml
- james.text.json
- james.text.strings

**Comment by fabriciofx** [comment]
@mdbs99 You're trying change the unit name, aren't you? So, before change their names, we need analyze what is the common concept round all these things, because if these concepts share the same unit, imply they *must* have something in common. Thus, let's see what Wikipedia says about them:

[XML](https://en.wikipedia.org/wiki/XML):
> In computing, Extensible Markup Language (XML) is a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable. (...) The design goals of XML emphasize simplicity, generality, and usability across the Internet.[5] It is a textual data format with strong support via Unicode for different human languages. 

[JSON](https://en.wikipedia.org/wiki/JSON)
> In computing, JavaScript Object Notation or JSON (/ˈdʒeɪsən/ JAY-sən),[1] is an open-standard file format that uses human-readable text to transmit data objects consisting of attribute–value pairs and array data types (or any other serializable value). (...) JSON is a language-independent data format.

[INI File](https://en.wikipedia.org/wiki/INI_file)
> The INI file format is an informal standard for configuration files for some platforms or software. INI files are simple text files with a basic structure composed of sections, properties, and values.

We can see some common terms among them: *standard*, *text* and *format*. But, to an INI file, it's a *informal* standard; *text* is too much vague. So, the best term is **format**. Therefore, the new names should be:

- `james.format.xml.*`
- `james.format.json.*`

What do you think?

**Comment by mdbs99** [comment]
I think you're right, thanks. I will change as you're proposing.
